=== dubaleko/Programming_in_Internet/laba 5/files/air.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="arrayair">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="aircraft" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="color" type="xs:string"/>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="range" type="xs:int"/>
                            <xs:element name="amount" type="xs:int"/>
                            <xs:element name="carrying" type ="xs:int"/>
                            <xs:element name="capacity" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dubaleko/Programming_in_Internet/laba 5/files/air.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type= "text/xsl" version="2.0" href = "air.xsl"?>
<arrayair  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="air.xsd">
    <aircraft>
        <color>black</color>
        <name>ATR - 72</name>
        <range>1300</range>
        <amount>1570</amount>
        <carrying>500</carrying>
        <capacity>10</capacity>
    </aircraft>
    <aircraft>
        <color>white</color>
        <name>Cy - 7</name>
        <range>1130</range>
        <amount>1350</amount>
        <carrying>300</carrying>
        <capacity>2</capacity>
    </aircraft>
    <aircraft>
        <color>green</color>
        <name>An - 12</name>
        <range>7200</range>
        <amount>5000</amount>
        <carrying>2000</carrying>
        <capacity>200</capacity>
    </aircraft>
</arrayair>
